"use strict";
const $=s=>document.querySelector(s),esc=v=>{const d=document.createElement("div");d.textContent=v??"";return d.innerHTML};
let state={person:"",personCategory:"investor",theme:"",period:30,view:"ledger",items:[],triage:[],selected:"",people:{},personItems:[],periods:[]};
async function api(url){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}
async function apiAuth(url,opt={},retried=false){const headers=new Headers(opt.headers||{});const token=sessionStorage.getItem("newsdeskWriteToken");if(token)headers.set("X-Newsdesk-Token",token);const r=await fetch(url,{...opt,headers});if(r.status===401&&!retried){const e=prompt("请输入 NEWSDESK 管理令牌（服务器 data/admin-token）");if(e){sessionStorage.setItem("newsdeskWriteToken",e.trim());return apiAuth(url,opt,true)}}if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}
function fmtTime(ts){return ts?new Date(ts*1000).toLocaleDateString("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit"}):"时间待核"}
function capitalLabel(x){return x.actor_kind==="personal"?"个人资本":x.actor_kind==="controlled_institution"?"受控机构资本":"关联机构行动"}
function statusLabel(x){return ({announced:"已宣布",contracted:"已签约",in_progress:"进行中",completed:"已完成",realized:"已实现"})[x.execution_status]||"状态待核"}
const categoryLabels={all:"全部人物",investor:"投资与资本",technology:"科技经营者",science_technology:"科技与产业研究",academic:"学术研究",public_intellectual:"思想与制度",policy:"政策行动者"};
const categoryOrder=["all","investor","technology","science_technology","academic","public_intellectual","policy"];
function renderPersonBrowser(){const totals=Object.fromEntries(categoryOrder.map(c=>[c,c==="all"?state.personItems.length:state.personItems.filter(x=>x.category===c).length]));$("#person-categories").innerHTML=categoryOrder.filter(c=>totals[c]).map(c=>`<button data-category="${c}" class="${state.personCategory===c?"on":""}"><span>${categoryLabels[c]}</span><em>${totals[c]}</em></button>`).join("")+`<small>一级选类别，右侧选人物</small>`;const visible=state.personItems.filter(x=>state.personCategory==="all"||x.category===state.personCategory).sort((a,b)=>b.published_count-a.published_count||b.signal_prior-a.signal_prior);const personButton=x=>`<button data-person="${esc(x.id)}" class="${x.published_count?"":"pending-person"} ${state.person===x.id?"on":""}" title="${x.published_count?"查看已核验行动":"人物已建档，尚无通过发布门禁的行动"}">${esc(x.name_zh||x.name)} <em>${x.published_count||"待补证"}</em></button>`;$("#people").innerHTML=`<span>${categoryLabels[state.personCategory]} · ${visible.length}</span><button data-person="" class="${state.person?"":"on"}">该类全部 <em>${visible.length}</em></button>${visible.map(personButton).join("")}`;bindPersonFilters()}
function bindPersonFilters(){document.querySelectorAll("[data-category]").forEach(b=>b.onclick=()=>{state.personCategory=b.dataset.category;state.person="";state.theme="";renderPersonBrowser();load()});document.querySelectorAll("[data-person]").forEach(b=>b.onclick=()=>{state.person=b.dataset.person;state.theme="";renderPersonBrowser();load()})}
async function loadFilters(){const [p,t]=await Promise.all([api("/api/persons"),api("/api/movement-themes")]);state.personItems=p.items;state.people=Object.fromEntries(p.items.map(x=>[x.id,x]));renderPersonBrowser();$("#themes").innerHTML=t.items.filter(x=>x.movement_count).map(x=>`<button data-theme="${esc(x.slug)}">${esc(x.name_zh)} <em>${x.movement_count}</em></button>`).join("");bindFilters()}
function bindFilters(){document.querySelectorAll("[data-theme]").forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;state.person="";activateTheme(b);renderPersonBrowser();switchView("ledger")});bindPeriods();$("#btn-triage").onclick=()=>switchView("triage")}
function switchView(view,period){state.view=view;if(period!==undefined)state.period=period;$("#btn-triage").classList.toggle("on",view==="triage");renderPeriods();const ledger=view==="ledger";$("#trends").style.display=ledger?"":"none";if(ledger){$("#detail").style.display="";Promise.all([load(),loadTrends()])}else{$("#detail").className="detail empty";$("#detail").style.display="none";loadTriage()}}
function activateTheme(b){document.querySelectorAll("[data-theme]").forEach(x=>x.classList.toggle("on",x===b))}
function periodAfter(){return state.period?Math.floor(Date.now()/1000)-state.period*86400:null}
function periodLabel(){return (state.periods.find(x=>x.days===state.period)||{}).label||"近 30 天"}
async function loadPeriods(){const data=await api("/api/movement-periods");state.periods=data.items;renderPeriods()}
// 数量直接印在按钮上：空切片是真实结论（那几天确实没有可核验行动），不该让人点进去才发现
function renderPeriods(){$("#periods").innerHTML=state.periods.map(x=>`<button data-view="ledger" data-period="${x.days}" class="${state.view==="ledger"&&state.period===x.days?"on":""} ${x.movement_count?"":"void"}" title="${x.movement_count?`${x.movement_count} 条行动 · ${x.person_count} 人`:"该区间没有通过发布门禁的行动"}">${x.label} <em>${x.movement_count}</em></button>`).join("");bindPeriods()}
function bindPeriods(){document.querySelectorAll("#periods [data-period]").forEach(b=>b.onclick=()=>switchView("ledger",Number(b.dataset.period)))}
async function load(){try{const q=new URLSearchParams({limit:"100",order:"recent"});const after=periodAfter();if(after)q.set("after",after);if(state.person)q.set("person",state.person);if(state.theme)q.set("theme",state.theme);const data=await api(`/api/movements?${q}`);state.items=data.items;const person=state.people[state.person];const label=periodLabel();$("#lens-title").textContent=person?`${person.name_zh||person.name}：行动时间线`:state.theme?"主题行动脉络":"看他们做什么。";const people=new Set(data.items.flatMap(x=>x.persons.map(p=>p.id))).size;$("#lens-copy").textContent=person?`共 ${data.total} 条已核验行动；按实际行动时间倒序，言论不计入。`:data.total?`${label}：${people} 人共 ${data.total} 条已核验行动。切换区间可比较不同时间尺度上的动作密度。`:`${label}内没有通过发布门禁的行动——这是结论，不是缺页：账本不会用言论或未核验线索填补空白。`;$("#count").textContent=`${data.total} 条行动 · ${label}`;$("#mode-note").textContent="按行动时间倒序 · 已核验且通过发布门禁";render()}catch(e){$("#count").textContent="加载失败";$("#cards").innerHTML=`<div class="empty error">${esc(e.message)}</div>`}}
async function loadTrends(){const after=periodAfter(),q=after?`?after=${after}`:"";const data=await api(`/api/movement-trends${q}`);$("#trends").innerHTML=data.items.filter(x=>x.movement_count>=2).slice(0,6).map(x=>`<div class="trend-card ${x.signal}"><span>${x.signal==="collective"?"多人共同方向":x.signal==="converging"?"正在汇聚":"单人轨迹"}</span><strong>${esc(x.name)}</strong><b>${x.person_count}</b><span> 人 · ${x.movement_count} 个行动${x.total_usd?` · 可加总口径 $${(Number(x.total_usd)/1e9).toFixed(1)}B`:""}</span></div>`).join("")}
async function loadMonitorStatus(){const x=await api("/api/movement-monitor-status");$("#monitor-status").textContent=`自动扫描每 15 分钟 · 近 ${x.window_days} 天覆盖 ${x.recent_people}/${x.tracked_people} 人 · ${x.candidates_pending_review} 条待复核`;$("#monitor-status").classList.toggle("coverage-warning",x.coverage_status!=="healthy");const tc=$("#triage-count");if(tc)tc.textContent=x.candidates_total??x.candidates_pending_review}
async function loadTriage(){$("#lens-title").textContent="候选分诊";$("#lens-copy").textContent="机器抽取的公开行动候选，尚未公开：rules-v1 来自新闻流；edgar-v1 来自 SEC 结构化申报（自带一次源链接，对象待人工按申报正文补全）。管理员核对后补全并发布或拒绝；发布仍需通过同一套证据门禁。";$("#count").textContent="加载中…";$("#mode-note").textContent="";try{const data=await apiAuth("/api/admin/movements?workflow=draft&limit=100");state.triage=data.items;$("#count").textContent=`${data.total} 条待分诊`;renderTriage()}catch(e){$("#count").textContent="需要管理令牌或加载失败";$("#cards").innerHTML=`<div class="empty error">${esc(e.message)}</div>`}}
function renderTriage(){if(!state.triage.length){$("#cards").innerHTML=`<div class="triage-intro">当前没有待分诊的候选。规则引擎会在每次刷新后把新抽取的公开行动放到这里等待核对。</div>`;return}const intro=`<div class="triage-intro">这些是<b>规则自动抽取</b>的候选，默认不公开。核对证据后：<b>发布</b> → 通过发布门禁进入公开账本；<b>拒绝</b> → 标记 rejected 并撤下。发布门禁本身不会因为分诊而放松。</div>`;const tc=x=>`<div class="tcard" data-id="${esc(x.id)}"><div class="meta"><span class="chip">${esc(x.persons.map(p=>p.name_zh||p.name).join(" / ")||"未归因")}</span><span class="chip">${esc(capitalLabel(x))}</span><span class="chip">${esc(statusLabel(x))}</span><span class="chip">${esc(x.verification_status)}</span><span class="chip">${esc(x.action_type)}</span></div><h2>${esc(x.title)}</h2>${x.object_text?`<p>对象：${esc(x.object_text)}${x.amount_value_text?` · 金额口径 ${esc(x.amount_value_text)}`:""}</p>`:`<div class="tcomplete"><input class="obj-in" type="text" placeholder="补充申报对象（按 SEC 正文，如：收购标的 / 主要持仓 / 任免人选）"><input class="amt-in" type="text" placeholder="金额口径（可选，如 $5 billion / 50亿美元）"></div>`}<div class="obs">${esc(x.observed_fact||"")}</div><div class="tev">${(x.evidence||[]).map(e=>`<div><span class="role">${esc(e.source_role)}</span><a href="${esc(e.url)}" target="_blank" rel="noopener">${esc(e.source_name||e.title||e.url)} ↗</a></div>`).join("")||'<span class="tmsg err">无证据</span>'}</div><div class="tacts">${x.object_text?`<button class="pub" data-act="publish">发布到公开账本</button>`:`<button class="pub" data-act="complete">补全并发布</button>`}<button class="rej" data-act="reject">拒绝</button></div><div class="tmsg" data-msg></div></div>`;$("#cards").innerHTML=intro+state.triage.map(tc).join("");document.querySelectorAll(".tcard").forEach(card=>{const id=card.dataset.id;card.querySelectorAll("[data-act]").forEach(btn=>btn.onclick=()=>btn.dataset.act==="complete"?completeAction(id,card):reviewAction(id,btn.dataset.act,card))})}
async function reviewAction(id,act,card){const btns=card.querySelectorAll("button");btns.forEach(b=>b.disabled=true);const msg=card.querySelector("[data-msg]");msg.className="tmsg";msg.textContent="提交中…";const payload=act==="publish"?{verification_status:"verified",workflow_status:"published",reason:"triage publish"}:{verification_status:"rejected",workflow_status:"withdrawn",reason:"triage reject"};try{await apiAuth(`/api/movement-review/${encodeURIComponent(id)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});msg.className="tmsg ok";msg.textContent=act==="publish"?"✓ 已发布到公开账本":"✓ 已拒绝并撤下";setTimeout(()=>{loadTriage();loadMonitorStatus();loadPeriods()},700)}catch(e){msg.className="tmsg err";msg.textContent=`失败：${e.message}`;btns.forEach(b=>b.disabled=false)}}
async function completeAction(id,card){const obj=(card.querySelector(".obj-in")?.value||"").trim();const amt=(card.querySelector(".amt-in")?.value||"").trim();const msg=card.querySelector("[data-msg]");if(!obj){msg.className="tmsg err";msg.textContent="请先按 SEC 申报正文补充『对象』再发布";return}const btns=card.querySelectorAll("button");btns.forEach(b=>b.disabled=true);msg.className="tmsg";msg.textContent="补全并过发布门禁中…";const payload={object_text:obj,reason:"triage complete+publish"};if(amt)payload.amount_value_text=amt;try{await apiAuth(`/api/movement-complete/${encodeURIComponent(id)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});msg.className="tmsg ok";msg.textContent="✓ 已补全并发布到公开账本";setTimeout(()=>{loadTriage();loadMonitorStatus();loadPeriods()},700)}catch(e){msg.className="tmsg err";msg.textContent=`发布门禁未通过：${e.message}`;btns.forEach(b=>b.disabled=false)}}
const actedAt=x=>x.occurred_from_ts||x.disclosed_ts||0;
function render(){if(!state.items.length){$("#cards").innerHTML=`<div class="notice">${esc(periodLabel())}内没有通过发布门禁的行动。系统不会为了填满页面而把言论、计划或未经核验的候选伪装成事实——换一个更长的区间可以看到更早的布局。</div>`;return}const card=x=>`<button class="card ${state.selected===x.id?"on":""}" data-id="${x.id}"><div><div class="meta"><span class="chip">${esc(x.persons.map(p=>p.name_zh||p.name).join(" / "))}</span><span class="chip">${esc(capitalLabel(x))}</span><span class="chip">${esc(statusLabel(x))}</span><span class="chip">${esc(x.verification_status)}</span></div><h2>${esc(x.title)}</h2><p>${esc(x.summary||x.observed_fact)}</p><div class="chips">${x.themes.map(t=>`<span class="chip">${esc(t.name_zh)}</span>`).join("")}</div></div><div class="metric"><b>${Math.round(x.materiality_score*100)}</b><span>行动重要性</span><br><span>行动 ${fmtTime(x.occurred_from_ts||x.disclosed_ts)}</span>${x.occurred_from_ts&&x.disclosed_ts!==x.occurred_from_ts?`<br><span>披露 ${fmtTime(x.disclosed_ts)}</span>`:""}</div></button>`;const section=(title,copy,items)=>`<section class="time-section"><header><h2>${title}</h2><span>${copy}</span><b>${items.length}</b></header>${items.map(card).join("")}</section>`;if(state.person||state.theme){$("#cards").innerHTML=section(esc(periodLabel()),"按行动时间倒序",state.items)}else{
// 按人分组，直接回答“这段时间各位分别干了什么”；同一行动涉及多人则在每人名下各出现一次
const groups=new Map();state.items.forEach(x=>x.persons.forEach(p=>{const g=groups.get(p.id)||{name:p.name_zh||p.name,items:[]};if(!g.items.some(y=>y.id===x.id))g.items.push(x);groups.set(p.id,g)}));
const ordered=[...groups.values()].sort((a,b)=>actedAt(b.items[0])-actedAt(a.items[0]));
$("#cards").innerHTML=ordered.map(g=>section(esc(g.name),`${g.items.length} 个行动 · 最近 ${fmtTime(actedAt(g.items[0]))}`,g.items)).join("")}
document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>show(b.dataset.id))}
function show(id){state.selected=id;render();const x=state.items.find(v=>v.id===id),d=$("#detail");d.className="detail";d.innerHTML=`<button class="close" aria-label="关闭">关闭</button><div class="detail-head"><span>${esc(x.persons.map(p=>p.name_zh||p.name).join(" / "))} · ${esc(capitalLabel(x))} · ${esc(statusLabel(x))}</span><h2>${esc(x.title)}</h2><p>${esc(x.summary)}</p></div><div class="split"><div><span>事实可信度</span><b>${Math.round(x.confidence*100)} / 100</b></div><div><span>行动重要性</span><b>${Math.round(x.materiality_score*100)} / 100</b></div><div><span>行动/披露时间</span><b>${fmtTime(x.occurred_from_ts)} / ${fmtTime(x.disclosed_ts)}</b></div><div><span>金额口径</span><b>${esc(x.amount_value_text||"未可靠提取")}</b></div></div><div class="fact"><label>已观察事实</label><p>${esc(x.observed_fact)}</p></div><div class="fact boundary"><label>分析边界</label><p>${esc(x.analytical_boundary)}</p></div><h3>人物归因</h3>${x.persons.map(p=>`<div class="fact"><label>${esc(p.role)} · ${Math.round(p.attribution_confidence*100)}</label><p>${esc(p.control_basis)}</p></div>`).join("")}<h3>证据账本</h3><div class="evidence">${x.evidence.map(e=>`<a href="${esc(e.url)}" target="_blank" rel="noopener"><span>${esc(e.source_role)}</span><b>${esc(e.source_name||e.title)}</b><span>原文 ↗</span></a>`).join("")||"<div class=notice>尚无合格证据，不能发布。</div>"}</div>`;d.querySelector(".close").onclick=()=>{d.className="detail empty";d.innerHTML="选择一条行动<br>查看资本归属、事实边界与逐项证据"}}
document.onkeydown=e=>{if(["INPUT","TEXTAREA"].includes(document.activeElement.tagName))return;if(e.key==="Escape")$("#detail .close")?.click();const i=state.items.findIndex(x=>x.id===state.selected);if(e.key==="j"&&state.items.length)show(state.items[Math.min(state.items.length-1,i+1)].id);if(e.key==="k"&&state.items.length)show(state.items[Math.max(0,i-1)].id);if(e.key==="o"&&i>=0&&state.items[i].evidence[0])window.open(state.items[i].evidence[0].url,"_blank","noopener")};
loadPeriods().then(loadFilters).then(()=>Promise.all([load(),loadTrends(),loadMonitorStatus()])).catch(e=>{$("#count").textContent="初始化失败";$("#cards").innerHTML=`<div class="empty error">${esc(e.message)}</div>`});
