"use strict";
const $=s=>document.querySelector(s),esc=v=>{const d=document.createElement("div");d.textContent=v??"";return d.innerHTML};
let state={person:"",theme:"",items:[],selected:""};
async function api(url){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}
function fmtTime(ts){return ts?new Date(ts*1000).toLocaleDateString("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit"}):"时间待核"}
function capitalLabel(x){return x.actor_kind==="personal"?"个人资本":x.actor_kind==="controlled_institution"?"受控机构资本":"关联机构行动"}
async function loadFilters(){const [p,t]=await Promise.all([api("/api/persons"),api("/api/movement-themes")]);$("#people-total").textContent=p.items.length;$("#people").innerHTML=p.items.filter(x=>x.published_count).map(x=>`<button data-person="${esc(x.id)}">${esc(x.name_zh||x.name)} <em>${x.published_count}</em></button>`).join("");$("#themes").innerHTML=t.items.filter(x=>x.movement_count).map(x=>`<button data-theme="${esc(x.slug)}">${esc(x.name_zh)} <em>${x.movement_count}</em></button>`).join("");bindFilters()}
function bindFilters(){document.querySelectorAll("[data-person]").forEach(b=>b.onclick=()=>{state.person=b.dataset.person;state.theme="";activate(b);load()});document.querySelectorAll("[data-theme]").forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;state.person="";activate(b);load()})}
function activate(b){document.querySelectorAll(".filters button").forEach(x=>x.classList.toggle("on",x===b))}
async function load(){try{const q=new URLSearchParams({limit:"100"});if(state.person)q.set("person",state.person);if(state.theme)q.set("theme",state.theme);const data=await api(`/api/movements?${q}`);state.items=data.items;$("#count").textContent=`${data.total} 条行动`;$("#mode-note").textContent="已核验且通过发布门禁";render()}catch(e){$("#count").textContent="加载失败";$("#cards").innerHTML=`<div class="empty error">${esc(e.message)}</div>`}}
function render(){if(!state.items.length){$("#cards").innerHTML=`<div class="notice">当前没有通过发布门禁的行动。系统不会为了填满页面而把言论、计划或未经核验的候选伪装成事实。</div>`;return}$("#cards").innerHTML=state.items.map(x=>`<button class="card ${state.selected===x.id?"on":""}" data-id="${x.id}"><div><div class="meta"><span class="chip">${esc(x.persons.map(p=>p.name_zh||p.name).join(" / "))}</span><span class="chip">${esc(capitalLabel(x))}</span><span class="chip">${esc(x.verification_status)}</span></div><h2>${esc(x.title)}</h2><p>${esc(x.summary||x.observed_fact)}</p><div class="chips">${x.themes.map(t=>`<span class="chip">${esc(t.name_zh)}</span>`).join("")}</div></div><div class="metric"><b>${Math.round(x.materiality_score*100)}</b><span>行动重要性</span><br><span>${fmtTime(x.disclosed_ts)}</span></div></button>`).join("");document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>show(b.dataset.id))}
function show(id){state.selected=id;render();const x=state.items.find(v=>v.id===id),d=$("#detail");d.className="detail";d.innerHTML=`<button class="close" aria-label="关闭">关闭</button><div class="detail-head"><span>${esc(x.persons.map(p=>p.name_zh||p.name).join(" / "))} · ${esc(capitalLabel(x))}</span><h2>${esc(x.title)}</h2><p>${esc(x.summary)}</p></div><div class="split"><div><span>事实可信度</span><b>${Math.round(x.confidence*100)} / 100</b></div><div><span>行动重要性</span><b>${Math.round(x.materiality_score*100)} / 100</b></div><div><span>行动/披露时间</span><b>${fmtTime(x.occurred_from_ts)} / ${fmtTime(x.disclosed_ts)}</b></div><div><span>金额口径</span><b>${esc(x.amount_value_text||"未可靠提取")}</b></div></div><div class="fact"><label>已观察事实</label><p>${esc(x.observed_fact)}</p></div><div class="fact boundary"><label>分析边界</label><p>${esc(x.analytical_boundary)}</p></div><h3>人物归因</h3>${x.persons.map(p=>`<div class="fact"><label>${esc(p.role)} · ${Math.round(p.attribution_confidence*100)}</label><p>${esc(p.control_basis)}</p></div>`).join("")}<h3>证据账本</h3><div class="evidence">${x.evidence.map(e=>`<a href="${esc(e.url)}" target="_blank" rel="noopener"><span>${esc(e.source_role)}</span><b>${esc(e.source_name||e.title)}</b><span>原文 ↗</span></a>`).join("")||"<div class=notice>尚无合格证据，不能发布。</div>"}</div>`;d.querySelector(".close").onclick=()=>{d.className="detail empty";d.innerHTML="选择一条行动<br>查看资本归属、事实边界与逐项证据"}}
document.onkeydown=e=>{if(["INPUT","TEXTAREA"].includes(document.activeElement.tagName))return;if(e.key==="Escape")$("#detail .close")?.click();const i=state.items.findIndex(x=>x.id===state.selected);if(e.key==="j"&&state.items.length)show(state.items[Math.min(state.items.length-1,i+1)].id);if(e.key==="k"&&state.items.length)show(state.items[Math.max(0,i-1)].id);if(e.key==="o"&&i>=0&&state.items[i].evidence[0])window.open(state.items[i].evidence[0].url,"_blank","noopener")};
loadFilters().then(load).catch(e=>{$("#count").textContent="初始化失败";$("#cards").innerHTML=`<div class="empty error">${esc(e.message)}</div>`});
